### ISSUE TITLE
Carrier And Shipment Method Settings Not Reflected Correctly

### ISSUE THREAD

**Issue by shubham-namdeo** [hotwax/fulfillment#1244]
## Current behavior

1. Carrier and Shipment method not reflected correctly if user changes tabs and refreshes the page.
2. When tracking code is voided, it is still reflected on list page.
3. An incorrect toast message is displayed when an already scanned item is scanned again after all items in the packing order have been scanned.

## Expected behavior

1. Carrier and shipment method should be correctly reflected.
2. If tracking code is voided, it should be reflected on list page.
3. Correct toast should be displayed for listed case.

## Environment details

Version- v3
Environment- UAT

## Additional information

1. https://jam.dev/c/7e591b87-5af0-4f46-a546-edc4202f0c8d
2. https://jam.dev/c/ef833280-4be3-4776-a576-6299d77617b3

**Comment by ravilodhi** [comment]
#2 and #3 Fixed in the following PR - https://github.com/hotwax/fulfillment/pull/1248

**Comment by ravilodhi** [comment]
I think #1 is fixed now, marking it dev complete.

**Comment by shubham-namdeo** [comment]
Issue #1 still persists: after refreshing the page, the product-store association with the method is not displayed.
https://jam.dev/c/e7410670-312c-43f4-856e-ee88cfd3a771

**Comment by ravilodhi** [comment]
#1 is Fixed now. Marking it dev complete.

**Comment by shubham-namdeo** [comment]
Working fine in dev, hence closing this ticket.
